"""Add description field to api_keys table

Revision ID: 49a27ada28b2
Revises: 661563b93f3d
Create Date: 2025-06-17 08:49:23.941653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a27ada28b2'
down_revision: Union[str, None] = '661563b93f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'description')
    # ### end Alembic commands ###
