"""Add role column to organization_members

Revision ID: 87865a36c440
Revises: be0694c4a9ab
Create Date: 2025-06-03 22:34:56.747757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87865a36c440'
down_revision: Union[str, None] = 'be0694c4a9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new enum values to the existing enum type
    # These must be committed before they can be used in the same transaction
    op.execute("ALTER TYPE organizationrole ADD VALUE IF NOT EXISTS 'developer'")
    op.execute("ALTER TYPE organizationrole ADD VALUE IF NOT EXISTS 'reporter'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values easily
    # The new enum values will remain but won't be used
    pass
    # ### end Alembic commands ###
