"""Initial baseline migration with compatibility_mode

Revision ID: d2a4ce715b34
Revises: 
Create Date: 2025-06-23 18:40:46.244351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a4ce715b34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'compatibility_mode',
               existing_type=sa.VARCHAR(length=50),
               comment='MCP compatibility mode: api_wrapper (default) or resource_connection',
               existing_comment='MCP server type: api_wrapper (default) or resource_connection',
               existing_nullable=False,
               existing_server_default=sa.text("'api_wrapper'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'compatibility_mode',
               existing_type=sa.VARCHAR(length=50),
               comment='MCP server type: api_wrapper (default) or resource_connection',
               existing_comment='MCP compatibility mode: api_wrapper (default) or resource_connection',
               existing_nullable=False,
               existing_server_default=sa.text("'api_wrapper'::character varying"))
    # ### end Alembic commands ###
