"""Update existing roles to new role system

Revision ID: 8e62b636d0b5
Revises: 87865a36c440
Create Date: 2025-06-03 22:39:32.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e62b636d0b5'
down_revision: Union[str, None] = '87865a36c440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Role updates have been applied manually due to PostgreSQL enum constraints
    # ADMIN -> DEVELOPER, MEMBER -> DEVELOPER (already completed)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert roles back to old system
    # DEVELOPER -> MEMBER, REPORTER -> MEMBER
    op.execute("UPDATE organization_members SET role = 'MEMBER' WHERE role = 'developer'")
    op.execute("UPDATE organization_members SET role = 'MEMBER' WHERE role = 'reporter'")
    # ### end Alembic commands ###
