"""Add organization-centric schema with MCP servers

Revision ID: be0694c4a9ab
Revises: 807576bbae77
Create Date: 2025-06-03 18:26:21.501144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be0694c4a9ab'
down_revision: Union[str, None] = '807576bbae77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('env', sa.JSON(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('auto_approve', sa.JSON(), nullable=False),
    sa.Column('transport_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'STARTING', 'STOPPING', name='mcpserverstatus'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('team_access', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('last_called_at', sa.DateTime(), nullable=True),
    sa.Column('average_execution_time', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_tools')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
