"""add_user_favorites_table

Revision ID: 82afefa65f8b
Revises: 57e5dcef2932
Create Date: 2025-06-06 16:38:10.517566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82afefa65f8b'
down_revision: Union[str, None] = '57e5dcef2932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
