"""Add server_type field to mcp_servers for connection mode selection

Revision ID: d5972937e80e
Revises: 725cb65d62b1
Create Date: 2025-06-20 08:57:57.269929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5972937e80e'
down_revision: Union[str, None] = '725cb65d62b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server_type column as nullable first
    op.add_column('mcp_servers', sa.Column('server_type', sa.String(length=50), nullable=True, comment='MCP server type: api_wrapper (default) or resource_connection'))
    
    # Set all existing servers to api_wrapper (maintaining compatibility)
    op.execute("UPDATE mcp_servers SET server_type = 'api_wrapper' WHERE server_type IS NULL")
    
    # Make the column non-nullable after setting default values
    op.alter_column('mcp_servers', 'server_type', nullable=False, server_default='api_wrapper')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'server_type')
    # ### end Alembic commands ###
