"""add_client_session_and_tool_call_log_tables_fixed

Revision ID: ed6ab4b75b6b
Revises: 8a155c2700b2
Create Date: 2025-06-11 23:02:36.378751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6ab4b75b6b'
down_revision: Union[str, None] = '8a155c2700b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('client_version', sa.String(), nullable=True),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('successful_calls', sa.Integer(), nullable=True),
    sa.Column('failed_calls', sa.Integer(), nullable=True),
    sa.Column('client_metadata', sa.JSON(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_sessions_project_id'), 'client_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_client_sessions_server_id'), 'client_sessions', ['server_id'], unique=False)
    op.create_table('tool_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_namespace', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'TIMEOUT', 'CANCELLED', name='callstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['client_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_logs_project_id'), 'tool_call_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_request_id'), 'tool_call_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_server_id'), 'tool_call_logs', ['server_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_session_id'), 'tool_call_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_status'), 'tool_call_logs', ['status'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_timestamp'), 'tool_call_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tool_name'), 'tool_call_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tool_namespace'), 'tool_call_logs', ['tool_namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_call_logs_tool_namespace'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_tool_name'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_timestamp'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_status'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_session_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_server_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_request_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_project_id'), table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_index(op.f('ix_client_sessions_server_id'), table_name='client_sessions')
    op.drop_index(op.f('ix_client_sessions_project_id'), table_name='client_sessions')
    op.drop_table('client_sessions')
    # ### end Alembic commands ###
