"""update_project_security_fields

Revision ID: 1bf3e7c6e5f5
Revises: e3fc9ce4be03
Create Date: 2025-06-12 12:24:52.725482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bf3e7c6e5f5'
down_revision: Union[str, None] = 'e3fc9ce4be03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 새로운 컬럼들을 nullable=True로 먼저 추가
    op.add_column('projects', sa.Column('sse_auth_required', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('message_auth_required', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('allowed_ip_ranges', sa.JSON(), nullable=True))
    
    # 2. 기존 데이터를 기반으로 새 컬럼들의 기본값 설정
    # require_auth가 False였던 경우 -> sse_auth_required=False, message_auth_required=False
    # require_auth가 True였던 경우 -> sse_auth_required=False (Cline 미지원), message_auth_required=True
    op.execute("""
        UPDATE projects 
        SET 
            sse_auth_required = FALSE,
            message_auth_required = COALESCE(require_auth, TRUE),
            allowed_ip_ranges = COALESCE(allowed_ips, '[]'::json)
    """)
    
    # 3. 새 컬럼들을 NOT NULL로 변경
    op.alter_column('projects', 'sse_auth_required', nullable=False)
    op.alter_column('projects', 'message_auth_required', nullable=False)
    
    # 4. 기존 컬럼들 삭제
    op.drop_column('projects', 'allow_sse_without_auth')
    op.drop_column('projects', 'security_settings')
    op.drop_column('projects', 'require_auth')
    op.drop_column('projects', 'allowed_ips')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 기존 컬럼들을 다시 추가
    op.add_column('projects', sa.Column('allowed_ips', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('require_auth', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('security_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('allow_sse_without_auth', sa.BOOLEAN(), autoincrement=False, nullable=True))
    
    # 2. 데이터 복원
    op.execute("""
        UPDATE projects 
        SET 
            require_auth = message_auth_required,
            allow_sse_without_auth = NOT sse_auth_required,
            allowed_ips = allowed_ip_ranges,
            security_settings = '{}'::json
    """)
    
    # 3. NOT NULL 제약 조건 추가
    op.alter_column('projects', 'require_auth', nullable=False)
    op.alter_column('projects', 'allow_sse_without_auth', nullable=False)
    
    # 4. 새 컬럼들 삭제
    op.drop_column('projects', 'allowed_ip_ranges')
    op.drop_column('projects', 'message_auth_required')
    op.drop_column('projects', 'sse_auth_required')
    
    # ### end Alembic commands ###
