"""Add WorkerConfig table for persistent scheduler settings

Revision ID: 725cb65d62b1
Revises: e1c7c04a3f23
Create Date: 2025-06-20 08:22:17.190527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725cb65d62b1'
down_revision: Union[str, None] = 'e1c7c04a3f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_check_interval', sa.Integer(), nullable=True, comment='Server status check interval in seconds'),
    sa.Column('coalesce', sa.Boolean(), nullable=True, comment='Merge duplicate jobs'),
    sa.Column('max_instances', sa.Integer(), nullable=True, comment='Maximum number of job instances'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Configuration description'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional configuration notes'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Configuration creation time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Last update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_configs_id'), 'worker_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_configs_id'), table_name='worker_configs')
    op.drop_table('worker_configs')
    # ### end Alembic commands ###
