"""add_server_logs_table

Revision ID: 8a155c2700b2
Revises: c0f8f6824b89
Create Date: 2025-06-11 14:21:24.146959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a155c2700b2'
down_revision: Union[str, None] = 'c0f8f6824b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('category', sa.Enum('CONNECTION', 'TOOL_EXECUTION', 'ERROR', 'STATUS_CHECK', 'CONFIGURATION', name='logcategory'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_logs_category_timestamp', 'server_logs', ['category', 'timestamp'], unique=False)
    op.create_index('idx_server_logs_level_timestamp', 'server_logs', ['level', 'timestamp'], unique=False)
    op.create_index('idx_server_logs_project_timestamp', 'server_logs', ['project_id', 'timestamp'], unique=False)
    op.create_index('idx_server_logs_server_timestamp', 'server_logs', ['server_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_server_logs_server_timestamp', table_name='server_logs')
    op.drop_index('idx_server_logs_project_timestamp', table_name='server_logs')
    op.drop_index('idx_server_logs_level_timestamp', table_name='server_logs')
    op.drop_index('idx_server_logs_category_timestamp', table_name='server_logs')
    op.drop_table('server_logs')
    # ### end Alembic commands ###
