"""Add is_admin field to users table

Revision ID: 67bd89d2da13
Revises: 1bf3e7c6e5f5
Create Date: 2025-06-13 13:47:53.277055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bd89d2da13'
down_revision: Union[str, None] = '1bf3e7c6e5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable with default value
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, default=False))
    
    # Step 2: Update existing records to have default value
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    
    # Step 3: Make column not nullable
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
