"""add_project_security_settings

Revision ID: e3fc9ce4be03
Revises: ed6ab4b75b6b
Create Date: 2025-06-12 12:06:01.469798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fc9ce4be03'
down_revision: Union[str, None] = 'ed6ab4b75b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기본값과 함께 컬럼 추가 (기존 데이터 호환성)
    op.add_column('projects', sa.Column('require_auth', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('projects', sa.Column('allow_sse_without_auth', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('projects', sa.Column('allowed_ips', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('security_settings', sa.JSON(), nullable=True))
    
    # 기본값 설정 후 server_default 제거 (향후 INSERT에는 모델의 default 사용)
    op.alter_column('projects', 'require_auth', server_default=None)
    op.alter_column('projects', 'allow_sse_without_auth', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'security_settings')
    op.drop_column('projects', 'allowed_ips')
    op.drop_column('projects', 'allow_sse_without_auth')
    op.drop_column('projects', 'require_auth')
    # ### end Alembic commands ###
