"""Add user management tables

Revision ID: 807576bbae77
Revises: cd3feaaa720f
Create Date: 2025-06-03 10:29:27.796392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807576bbae77'
down_revision: Union[str, None] = 'cd3feaaa720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('organization_members', 'is_default')
    # ### end Alembic commands ###
