"""add project activities table

Revision ID: 51bf78f0b48a
Revises: a1b2c3d4e5f6
Create Date: 2025-06-21 11:14:53.598774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51bf78f0b48a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_activities_action_created', 'project_activities', ['action', 'created_at'], unique=False)
    op.create_index('idx_project_activities_project_created', 'project_activities', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_project_activities_severity', 'project_activities', ['severity', 'created_at'], unique=False)
    op.create_index('idx_project_activities_target', 'project_activities', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_project_activities_user_created', 'project_activities', ['user_id', 'created_at'], unique=False)
    op.alter_column('mcp_servers', 'args',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('mcp_servers', 'env',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'env',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('mcp_servers', 'args',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('idx_project_activities_user_created', table_name='project_activities')
    op.drop_index('idx_project_activities_target', table_name='project_activities')
    op.drop_index('idx_project_activities_severity', table_name='project_activities')
    op.drop_index('idx_project_activities_project_created', table_name='project_activities')
    op.drop_index('idx_project_activities_action_created', table_name='project_activities')
    op.drop_table('project_activities')
    # ### end Alembic commands ###
